// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1amJPMoPzfrMfhrQL11NrZLY4uxeV9A',
    appId: '1:640178078797:web:7587a286b193cbc936c804',
    messagingSenderId: '640178078797',
    projectId: 'gasra-monitoring-notif',
    authDomain: 'gasra-monitoring-notif.firebaseapp.com',
    storageBucket: 'gasra-monitoring-notif.firebasestorage.app',
    measurementId: 'G-FE4PJ37WXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgA1uikbcJEGyTr_s6nRLpuFOAdE7KbA',
    appId: '1:640178078797:android:6e123909b0c356ac36c804',
    messagingSenderId: '640178078797',
    projectId: 'gasra-monitoring-notif',
    storageBucket: 'gasra-monitoring-notif.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ1amJPMoPzfrMfhrQL11NrZLY4uxeV9A',
    appId: '1:640178078797:web:d7923e588636303536c804',
    messagingSenderId: '640178078797',
    projectId: 'gasra-monitoring-notif',
    authDomain: 'gasra-monitoring-notif.firebaseapp.com',
    storageBucket: 'gasra-monitoring-notif.firebasestorage.app',
    measurementId: 'G-K1NEKQT4GD',
  );
}
